#!/usr/bin/env bash

# borrowed from btrfs-assistant
# see here: https://gitlab.com/btrfs-assistant/btrfs-assistant/-/blob/main/src/btrfs-assistant

ID=$(id -u)
if [[ "$ID" == "0" ]]; then
    export XDG_RUNTIME_DIR=$(mktemp -d)
fi

# extract the value of --xdg-desktop if it is passed and put all other args in params
for i in "$@"; do
    case $i in
        -x=*|--xdg-desktop=*)
            export XDG_CURRENT_DESKTOP="${i#*=}"
            shift
        ;;
        -r=*|--xdg-runtime=*)
            export XDG_RUNTIME_DIR="${i#*=}"
            shift
        ;;
        -t=*|--platformtheme=*)
            export QT_QPA_PLATFORMTHEME="${i#*=}"
            shift
        ;;
        -p=*|--platform=*)
            export QT_QPA_PLATFORM="${i#*=}"
            shift
        ;;
        -d=*|--display=*)
            export WAYLAND_DISPLAY="${i#*=}"
            shift
        ;;
        *)
            params="${params} ${i}"
            shift
        ;;
    esac
done

cachyos-pi-bin ${params}
