#!/usr/bin/env bash

# Elevate
if [[ $EUID -ne 0 ]]; then
    exec pkexec /usr/bin/cachyos-pi cachyos-pi-bin "$@"
    exit 1
fi

# Restore some variables from parent process
while IFS= read -rd '' var; do export "$var"; done < <(grep --null-data -ae "^\(XDG_CURRENT_DESKTOP\|WAYLAND_DISPLAY\|XDG_RUNTIME_DIR\|LOGNAME\|XAUTHORITY\|QT_STYLE_OVERRIDE\|HOME\|XDG_SESSION_TYPE\|XCURSOR_SIZE\|LC_.*\|LANG\|LANGUAGE\|QT_WAYLAND_FORCE_DPI\|\)=.*\$" /proc/$PPID/environ)
if [[ -v WAYLAND_DISPLAY ]]; then
    export WAYLAND_DISPLAY="$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY"
fi

export XDG_RUNTIME_DIR="/run/user/0"
exec /usr/bin/cachyos-pi-bin "$@"
